### ISSUE TITLE
Building with pkg

### ISSUE THREAD

**Issue by JulesTopart** [neojski/status-icon#2]
Building works in a sense. But pkg use a particular strategy to handle assets files. When I launch my compiled application I get this error : 
```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\snapshot\Botly-Agent\node_modules\electron-prebuilt\dist\electron.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1376:13)
    at startup (internal/bootstrap/node.js:320:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:660:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:660:3)
```

**Comment by neojski** [comment]
Could you provide reproduction steps?

**Comment by neojski** [comment]
Have you tried the tip of the repo? I think the current package in npm doesn't work for me but the tip of the repo does.
I'm currently having some problems signing into npm but I'll publish a new package shortly.

**Comment by neojski** [comment]
It should be fixed now. Please reopen if it still doesn't work for you (with repro steps if possible)
